sudo: required
services:
  - docker

before_install:
  - docker build -t lvivian89/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lvivian89/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-018215154053"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY